#!/bin/bash
# Email alert cron job script for ClamAV
# Email notifications in case of infections found will be sent

# Directories to scan
SCAN_DIR="/home /tmp /var"
# Location of log file
LOG_FILE="/var/log/clamav/auto_clam_scan.log"
# Uncomment to have scan remove files
# AGGRESSIVE=1
# Uncomment to have scan not remove files
AGGRESSIVE=0
# Email Subject
SUBJECT="Potential Threat Detected"
# Email To
EMAIL="pkakra@fanshaweonline.ca"
# Email From
EMAIL_FROM="tempsomething2k23@gmail.com"

# Function to check for infections and send an email alert
check_scan() {
    # If there were infected files detected, send email alert
    if [ $(tail -n 12 ${LOG_FILE} | grep -i 'Infected' | grep -v '0' | wc -l) -ne 0 ]; then
        # Count number of infections
        SCAN_RESULTS=$(tail -n 10 $LOG_FILE | grep 'Infected files')
        INFECTIONS=$(echo $SCAN_RESULTS | awk '{print $NF}')
        
        # Create temporary email message
        EMAILMESSAGE=$(mktemp /tmp/virus-alert.XXXXX)
        echo "To: ${EMAIL}" > ${EMAILMESSAGE}
        echo "From: ${EMAIL_FROM}" >> ${EMAILMESSAGE}
        echo "Subject: ${SUBJECT}" >> ${EMAILMESSAGE}
        echo "Importance: High" >> ${EMAILMESSAGE}
        echo "X-Priority: 1" >> ${EMAILMESSAGE}
        echo "***A Scan was carried out by pkakra***" >> ${EMAILMESSAGE}

        # Add scan results based on aggressive flag
        if [ $AGGRESSIVE -eq 1 ]; then
            echo -e "\n$(tail -n $((10 + INFECTIONS * 2)) $LOG_FILE)" >> ${EMAILMESSAGE}
        else
            echo -e "\n$(tail -n $((10 + INFECTIONS)) $LOG_FILE)" >> ${EMAILMESSAGE}
        fi

        # Send the email
        sendmail -t < ${EMAILMESSAGE}
    fi
}

# Run ClamAV scan based on aggressive setting
if [ $AGGRESSIVE -eq 1 ]; then
    /usr/bin/clamscan -ri --remove $SCAN_DIR >> $LOG_FILE
else
    /usr/bin/clamscan -ri $SCAN_DIR >> $LOG_FILE
fi

# Call the check_scan function to send email if infections are found
check_scan
