#!/bin/bash
# Email alert cron job script for ClamAV
# Email notifications in case of infections found or NO infections will be sent

# Directories to scan
SCAN_DIR="/home /tmp /var"
# Location of log file
LOG_FILE="/var/log/clamav/auto_clam_scan.log"
# Uncomment to have scan remove files
# AGGRESSIVE=1
# Uncomment to have scan not remove files
AGGRESSIVE=0
# Email Subject for Infected Files
SUBJECT_INFECTED="Potential Threat Detected"
# Email Subject for No Infections
SUBJECT_NO_THREAT="No Threats Detected"
# Email To
EMAIL="pkakra@fanshaweonline.ca"
# Email From
EMAIL_FROM="tempsomething2k23@gmail.com"

# Function to send email notification
send_email() {
    local subject="$1"
    local message="$2"

    EMAILMESSAGE=$(mktemp /tmp/virus-alert.XXXXX)
    echo "To: ${EMAIL}" > ${EMAILMESSAGE}
    echo "From: ${EMAIL_FROM}" >> ${EMAILMESSAGE}
    echo "Subject: ${subject}" >> ${EMAILMESSAGE}
    echo "Importance: High" >> ${EMAILMESSAGE}
    echo "X-Priority: 1" >> ${EMAILMESSAGE}
    echo "$message" >> ${EMAILMESSAGE}
    sendmail -t < ${EMAILMESSAGE}
}

# Function to check for infections and send an email alert
check_scan() {
    # Check for infected files in the scan log
    INFECTED_COUNT=$(tail -n 12 ${LOG_FILE} | grep -i 'Infected' | grep -v '0' | wc -l)

    if [ $INFECTED_COUNT -ne 0 ]; then
        # Infections found, send email for detected threats
        SCAN_RESULTS=$(tail -n 10 $LOG_FILE | grep 'Infected files')
        INFECTIONS=$(echo $SCAN_RESULTS | awk '{print $NF}')
        
        # Construct the message with scan results
        MESSAGE="***A Scan was carried out by pkakra***\n"
        if [ $AGGRESSIVE -eq 1 ]; then
            MESSAGE+="\n$(tail -n $((10 + INFECTIONS * 2)) $LOG_FILE)"
        else
            MESSAGE+="\n$(tail -n $((10 + INFECTIONS)) $LOG_FILE)"
        fi
        send_email "$SUBJECT_INFECTED" "$MESSAGE"
    else
        # No infections found, send email for no threats detected
        MESSAGE="***A Scan was carried out by pkakra***\n\nNo infections were detected during the scan."
        send_email "$SUBJECT_NO_THREAT" "$MESSAGE"
    fi
}

# Run ClamAV scan based on aggressive setting
if [ $AGGRESSIVE -eq 1 ]; then
    /usr/bin/clamscan -ri --remove $SCAN_DIR >> $LOG_FILE
else
    /usr/bin/clamscan -ri $SCAN_DIR >> $LOG_FILE
fi

# Call the check_scan function to send email
check_scan
